export const LAY_DANH_SACH_SAN_PHAM_REQUEST = "LAY_DANH_SACH_SAN_PHAM_REQUEST";
export const LAY_DANH_SACH_SAN_PHAM_SUCCESS = "LAY_DANH_SACH_SAN_PHAM_SUCCESS";
export const LAY_DANH_SACH_SAN_PHAM_FAIL = "LAY_DANH_SACH_SAN_PHAM_FAIL";